from .som import SelfOrganizingMap
from .cell import CellMap
from .fluxmodes import CellMapColor, CellMapMagColor, CellMapFluxFluxRatio, CellMapLnFluxFluxRatio, CellMapLupticolorLupticolorluptitude, CellMapLupticolor, CellMapColorLuptitcolor, CellMapColorColorMagnitude, CellMapColorLupticolorluptitude, CellMapLupticolorLupticolorluptitudeIvarDeep, CellMapLupticolorLupticolorluptitude_withoutY, CellMapLupticolorLupticolorluptitude_softb, CellMapLupticolorLupticolorluptitude_wideIGRZ_withoutY, CellMapLupticolorLupticolorluptitude_wideIRZ, CellMapLupticolorLupticolorluptitude_wideIRZ_withoutY
 
from .plots import histogramize

from .cellprob import CellMapWideProbabilistic

read = CellMap.read
